name: CI

on:
  push:
  pull_request:

jobs:
  cargo-build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cargo cache
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
      - name: Build
        run: cargo build
        working-directory: src-tauri/

  cargo-clippy:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cargo cache
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-clippy-
      - name: Clippy
        run: cargo clippy -- --deny warnings
        working-directory: src-tauri/

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Format check
        run: cargo fmt --check
        working-directory: src-tauri/

  cargo-test:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cargo cache
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
      - name: Make dist dir
        run: mkdir dist/
      - name: Test
        run: cargo test --all-targets --all-features
        working-directory: src-tauri/

  cargo-audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Audit
        run: cargo audit
        working-directory: src-tauri/

  node-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build

  node-eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: ESLint
        run: npx eslint .

  node-prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Prettier
        run: npx prettier --check .

  tauri-build:
    runs-on: windows-2022
    needs:
      - cargo-build
      - node-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cargo cache
        uses: actions/cache@v4.0.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-tauri-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Tauri build
        run: npm run tauri build
